config/routes.rb
Rails.application.routes.draw do

  # devise
  devise_for :users
  # Home Controller
  root  'homes#top'
  #タグ
  get 'tags/:tag', to: 'posts#index', as: :tag
  #Posts Controller
  resources :posts do
  resource :favorites, only: [:create, :destroy]
  end
  #Users Controller
  resources :users, only: [:show, :edit, :update, :index, :new ]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
   # Validation
    validates :title, presence: true
    validates :body, presence: true
    validates :body, length: { maximum: 200 }

    #関連付け
	belongs_to :user

	#タグ付機能
	acts_as_taggable

	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }

  has_many :posts, dependent: :destroy

  attachment :profile_image
  
  has_many :favorites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 # before_action :authenticate_user!
	   before_action :configure_permitted_parameters, if: :devise_controller?
     before_action :set_search

  def set_search
    #@search = Article.search(params[:q])
    @search = Post.ransack(params[:q]) #ransackメソッド推奨
    @search_posts = @search.result.page(params[:page])
  end

	def after_sign_in_path_for(resource)
    posts_path # ログイン後に遷移するpathを設定
  end

  def after_sign_out_path_for(resource)
    root_path # ログアウト後に遷移するpathを設定
  end

  protected
    def configure_permitted_parameters
	   devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:introduction,:email])
    end
  end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    favorite = @post.favorites.new(user_id: current_user.id)
    favorite.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!

  def new
    @post = Post.new
  end

  def create
  	@post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to post_path(@post.id), notice: 'Post was successfully created.'
    else
      @posts = Post.all
      @user = current_user
      render action: :index
    end
  end

  def index
   @post = Post.new
   @user = current_user
   if params[:tag]
      @posts = Post.tagged_with(params[:tag]).page(params[:page]).reverse_order
    else
      @posts = Post.page(params[:page]).reverse_order
    end
  end

  def show
   @post_new = Post.new
   @post = Post.find(params[:id])
   @user = @post.user
  end

  def edit
   @post = Post.find(params[:id])
   unless current_user.id == @post.user.id
   redirect_to posts_path
   end
   @user = current_user
  end

  def update
   @post = Post.find(params[:id])
   if @post.update(post_params)
   redirect_to post_path(@post), notice: 'Post was successfully created.'
   else
   render action: :edit
   end
  end


  def destroy
   @post = Post.find(params[:id])
   @post.destroy
   redirect_to posts_path
  end

  private
  def post_params
   params.require(:post).permit(:title, :body, :tag_list)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

 def new
   @post = Post.new
 end

 def index
   @users = User.page(params[:page]).reverse_order
   @posts = Post.all
   @post = Post.new
   @user = current_user
 end

 def show
   @user = User.find(params[:id])
   @post = Post.new
   @posts = @user.posts
 end

 def edit
   @user = User.find(params[:id])
 end

 def update
   @user = User.find(params[:id])
   if @user.update(user_params)
     redirect_to user_path(@user.id), notice: 'User was successfully created.'
   else
     render action: :edit
   end
 end

 def ensure_correct_user
   if current_user.id !=  params[:id].to_i
      redirect_to user_path(current_user.id)
   end
 end

 private
 def user_params
   params.require(:user).permit(:name,:introduction,:profile_image)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/create.js.erb
$(".post_<%= @post.id %>").html("<%= j(render 'posts/favorite', post: @post) %>")

app/views/favorites/destroy.js.erb
$(".post_<%= @post.id %>").html("<%= j(render 'posts/favorite', post: @post) %>")

app/views/homes/about.html.erb
about

app/views/homes/top.html.erb
<div class="container2">
  <div class="row">
    <% if flash[:notice] %>
    <% end %>
    <div class="col-xs-12">
      <div id="hero">

        <div id="theTarget" class="skipper">
          　　<div class="image4"></div>
          　　<div class="image2"></div>
          　　<div class="image3"></div>
          　　<div class="image1"></div>
        </div>

        <div class="tagline">
         <h2>夢日記へようこそ<h2>
         ヘッダーより新規登録してご利用ください
        </div>

     </div>
   </div>
 </div>
</div>

app/views/layouts/_form.html.erb
<div class="newbox">
	<%= form_for(post) do |f| %>
	<% if post.errors.any? %>
	<div id="error_explanation">
		<h2>
			<%= pluralize(post.errors.count, "error") %> prohibited
			this book from being saved:
		</h2>
		<ul>
			<% post.errors.full_messages.each do |msg|%>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<div class="cp_iptxt">
		<%= f.text_field :title, :placeholder => "タイトル" %>
		<i class="fa fa-book fa-lg fa-fw" ></i>
	</div>
	<div class="cp_iptxt">
		<%= f.text_area :body,:placeholder => "内容" %>
		<i class="fa fa-file-text-o fa-lg"></i>
	</div>
	<div class="cp_iptxt">
		<%= f.text_field :tag_list,:placeholder => "タグを記入" %>
		<i class="fa fa-smile-o fa-lg"></i> 
	</div>
	<%= f.submit '投稿する', class: "btn btn-border-shadow blue" %>
	<% end %>
</div>

app/views/layouts/_postform.html.erb
<%= form_with(model: post, local: true) do |form| %>
<% if post.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(post.errors.count, "error") %> prohibited this dream from being saved:</h2>

  <ul>
    <% post.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :どんな夢 %><br>
  <%= form.text_field :title %>
</div>

<div class="field">
  <%= form.label :何があったの %><br>
  <%= form.text_area :body,:placeholder => "例：山に登った" %>
</div>

<div class="field">
  <%= form.label :タグを編集する %><br>
  <%= form.text_field :tag_list %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/layouts/_userform.html.erb
<div class="userbox">
      <span class="userbox-circle1">会</span><span class="userbox-circle2">情</span>
      <table class='table'>
        <div class="user-edit-image">
                  <%= attachment_image_tag user, :profile_image, class: "img-circle pull-left profile-thumb",fallback: "girl.jpg",size: "100x100" %>
                </div>
        <tr>
          <th>お名前</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>ひとこと</th>
          <td><%= simple_format(user.introduction) %></td>
        </tr>
      </table>
      <div class="btn-wrap">
        <%= link_to "マイページ編集" ,edit_user_path(user), class: "btn btn-border-shadow green" %><br><br>
        </div>
    </div>

app/views/layouts/application.html.erb
<html>
<head>
  <title>夢日記</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <% if user_signed_in? %>
  <header header class="header-box">
    <div class="header-box2">
    <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span class="logo"><%= link_to "夢日記","/" %>
          </span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li> <%= link_to 'マイページ', user_path(current_user.id), class: "btn btn-border-shadow w" %></li>
            <li><%= link_to "ユーザー一覧","/users", class: "btn btn-border-shadow w" %></li>
            <li><%= link_to "投稿一覧","/posts", class: "btn btn-border-shadow w" %></li>
            <li><%= link_to "ログアウト",destroy_user_session_path, class: "glyphicon glyphicon-log-out logout btn btn-border-shadow w",method: :delete %></li>
          </ul>
        </nav>

      </div>
    </div>
  </header>


  <% else %>
  <header header class="header-box">
    <div class="header-box2">

    <div class="container">
      <nav class="nav navbar-nav navbar-left">
        <span class="logo">夢日記</span>
      </nav>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "新規登録","/users/sign_up",class: "btn btn-border-shadow w"  %></li>
          <li><%= link_to "ログイン","/users/sign_in",class: "btn btn-border-shadow w"  %></li>
        </ul>
      </nav>
    </div>
    </div>
  </header>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_favorite.html.erb
          <td>
            <% if post.favorited_by?(current_user) %>
            <%= link_to post_favorites_path(post, redirect_id: 0), method: :delete, remote: true do %>
            <span class="fa fa-thumbs-up fa-lg"><%= post.favorites.count %></span>
            <% end %>
            <% else %>
            <%= link_to post_favorites_path(post, redirect_id: 0), method: :post, remote: true do %>
            <span class="fa fa-thumbs-o-up fa-lg"><%= post.favorites.count %></span>
            <% end %>
            <% end %>
          </td>

app/views/posts/edit.html.erb
<div class="posteditbox">

<h2>夢の内容を編集する</h2>
<%= render :partial => 'layouts/postform', :locals => {:post => @post}%>

<%= link_to '詳細ページに戻る', @post ,class: "btn btn-border-shadow"%> |
<%= link_to '一覧に戻る', posts_path,class: "btn btn-border-shadow" %>
</div>

app/views/posts/index.html.erb
<div class="container">
    <p id="notice"><%= notice %></p>
    <div class="row">
      <div class="col-xs-4">
        <%= render :partial => 'layouts/userform', :locals => {:user => @user}%>
        <%= render :partial => 'layouts/form', :locals => {:post => @post}%>
      </div>
      <div class="col-xs-8">
        <div class="postindexbox">
          <h1 class="text-center">みんなが投稿した夢</h1>
          <table class='table table-hover table-inverse'>
            <thead>
              <tr>
                <th></th>
                <th><%= sort_link(@search, :title, 'どんな夢？') %></th>
                <th>何をしたの？</th>
                <th><%= sort_link(@search, :created_at, '投稿日') %></th>
                <th>タグ</th>
              </tr>
            </thead>
            <tbody>
              <% @posts.each do |post| %>
              <tr>
                <td><%= link_to user_path(post.user) do %>
                  <%= attachment_image_tag post.user, :profile_image,  class: "img-circle pull-left profile-thumb", fallback: "girl.jpg", size: "50x50" %><% end %></td>
                <td><%= link_to post.title,post %></td>
                <td><%= simple_format(post.body) %></td>
                <td><%= time_ago_in_words(post.created_at) %>前</td>
                <td><%= raw(post.tag_list.map { |t| link_to t, posts_path(tag: t) }.join(', ')) %></td>
              </tr>
              <% end %>
              <div class="pagebox">
              　　<%= paginate @posts %>
            </div>
            </tbody>
          </table><br>
        </div>
      </div>
    </div>
  </div>

app/views/posts/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="row">
    <div class="col-xs-4">
      <%= render :partial => 'layouts/userform', :locals => {:user => @user}%>
      <%= render :partial => 'layouts/form', :locals => {:post => @post}%>
    </div>
    <div class="col-xs-8">
      <div class="postdetailbox">
          <h2 class="text-center">
            <%= @post.title %>
          </h2>
          <tr>
          <th><%= simple_format(@post.body) %></th>
          <th>タグ： <%= raw(@post.tag_list.map { |t| link_to t, tag_path(t) }.join(',')) %></th><br>
           <th><%= time_ago_in_words(@post.created_at) %>前に投稿</th>
          </tr><br><br>
          <tr>
          <th><%= link_to '編集する', edit_post_path(@post), class: "btn btn-border-shadow yellow" %></th>
          <th><%= link_to '投稿を消去', post_path(@post), method: :delete, class: "btn btn-border-shadow red" %></th>
          <div class="post_<%= @post.id %> btn">
          <%= render :partial => 'posts/favorite', :locals => {:post => @post} %>
          </div>
        </tr>
      </div>
      <div class="detail1">
        見るとちょっと危険かも？<h3>警告夢とは</h3>
        悪夢は不吉なことの予兆と言われることがあります<br>
        怖い夢を見たら普段の行動を省みたり、新しいことなどをはじめてみましょう<br>
      </div>
      <div class="detail2">
        見るとラッキー！<h3>縁起のいい夢</h3>
        皆さんも一度は聞いたことがあるであろう「一富士二鷹三茄子」<br>
        実は続きがあるのご存知でしたか？<br>
        それは「四扇五煙草六座頭」、流石に座頭が夢に出てくることはないかもしれませんが<br>
        うちわやタバコなら皆さんの中にも見たことがある方がいそうですね
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
	<div class="usereditbox">
				<% if @user.errors.any? %>
				<div id="error_explanation">
					<h2><%= pluralize(@user.errors.count, "error") %> prohibited
					this book from being saved:</h2>
					<ul>
						<% @user.errors.full_messages.each do |msg|%>
						<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
				<% end %>
				<div>
				  <p>登録されているEmail</p>
				  <p><%= current_user.email %></p>
			    </div>
				<%= form_for (@user) do |f| %>
				<div>
					<label>お名前</label>
					<%= f.text_field :name %>
				</div><br>
				<div>
					<label>プロフィール画像を投稿</label>
					<%= f.attachment_field :profile_image %>
				</div><br>
				<div>
					<label>ひとこと</label><br>
					<%= f.text_area :introduction %>
				</div>
				<div>
					<%= f.submit "編集内容を更新する" %>
				</div>
				<% end %><br>
                <%= link_to "パスワードの変更と退会はこちら", edit_user_registration_path(current_user),class: "btn btn-border-shadow" %> 
	</div>

app/views/users/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-xs-4">
  <%= render :partial => 'layouts/userform', :locals => {:user => @user}%>
   <%= render :partial => 'layouts/form', :locals => {:post => @post}%>
 </div>
  <div class="col-xs-8">
    <div class="userindexbox">
      <h1 class="text-center">おともだち</h1>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>お名前</th>
            <th>ひとこと</th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, class: "img-circle pull-left profile-thumb", fallback: "girl.jpg", size: "50x50" %></td>
            <td><%= user.name %></td>
            <td><%= user.introduction %></td>
            <td><%= link_to '夢をみる',user_path(user.id),class: "btn btn-border-shadow aq" %></td>
          </tr>
          <% end %>
          <div class="pagebox">
              <%= paginate @users %>
            </div>
        </tbody>
      </table><br>
    </div>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
 <p id="notice"><%= notice %></p>
 <div class="row">
  <div class="col-xs-4">
   <%= render :partial => 'layouts/userform', :locals => {:user => @user}%>
   <%= render :partial => 'layouts/form', :locals => {:post => @post}%>
  </div>
  <div class="col-xs-8">
   <div class="mypagebox">
    <h1 class="text-center"><%= @user.name %>のみた夢</h1>
    <table class='table table-hover table-inverse'>
     <thead>
      <tr>
       <th><%= sort_link(@search, :title, 'どんな夢？') %></th>
       <th>なにがおきたの？</th>
       <th><%= sort_link(@search, :created_at, '投稿日') %></th>
       <th>タグ</th>
       <% @posts.each do |post| %>
       <tr>
        <td><%= link_to post.title, post %></td>
        <td><%= simple_format(post.body) %></td>
        <td><%= time_ago_in_words(post.created_at) %>前</td>
        <td><%= post.tag_list %></td>
       </tr>
       <% end %>
      </tr>
     </thead>
    </table><br>
   </div>
  </div>
 </div>
</div>